name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master] # 同时支持 main 和 master 分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # 部署整个仓库内容
          branch: gh-pages # 部署到 gh-pages 分支
          clean: true # 清理旧文件
